# Generated by Django 4.2.24 on 2025-09-15 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_producto_descripcion_alter_producto_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='stock',
            new_name='cantidad',
        ),
    ]
